# Generated by Django 6.0.4 on 2026-04-25 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freight_type', models.CharField(choices=[('PerQuantity', 'Per Quantity'), ('Fixed', 'Fixed'), ('Guaranteed', 'Guaranteed')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freights', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freights', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freights', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Freight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnFreight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freight_type', models.CharField(choices=[('PerQuantity', 'Per Quantity'), ('Fixed', 'Fixed'), ('Guaranteed', 'Guaranteed')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_freights', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_return_freights', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_freights', to='sales.creditnote')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_freights', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Return Freight',
                'ordering': ['-created_at'],
            },
        ),
    ]
