# Generated by Django 5.2.13 on 2026-04-27 09:10

from django.db import migrations


def create_default_units(apps, schema_editor):
    Unit = apps.get_model('masters', 'Unit')
    default_units = [
        ('MT', 'Metric Tonne', 'Weight measurement in metric tonnes (1000 kg)'),
        ('KG', 'Kilogram', 'Weight measurement in kilograms'),
        ('LTR', 'Litre', 'Volume measurement in litres'),
        ('PCS', 'Pieces', 'Count/quantity in individual pieces'),
        ('TON', 'Ton', 'Weight measurement in tons (2000 lbs)'),
        ('QTL', 'Quintal', 'Weight measurement in quintals (100 kg)'),
    ]
    for code, name, description in default_units:
        Unit.objects.get_or_create(code=code, defaults={'name': name, 'description': description})


def create_default_countries(apps, schema_editor):
    Country = apps.get_model('masters', 'Country')
    default_countries = [
        ('IND', 'India', True),
        ('USA', 'United States', True),
        ('GBR', 'United Kingdom', True),
        ('CHN', 'China', True),
    ]
    for code, name, is_active in default_countries:
        Country.objects.get_or_create(code=code, defaults={'name': name, 'is_active': is_active})


def create_default_states(apps, schema_editor):
    State = apps.get_model('masters', 'State')
    Country = apps.get_model('masters', 'Country')

    # Get India (should be first with default=1)
    india, _ = Country.objects.get_or_create(code='IND', defaults={'name': 'India', 'is_active': True})

    indian_states = [
        ('24', 'Gujarat'),
        ('27', 'Maharashtra'),
        ('29', 'Karnataka'),
        ('33', 'Tamil Nadu'),
        ('36', 'Telangana'),
        ('23', 'Madhya Pradesh'),
        ('22', 'Chhattisgarh'),
        ('08', 'Rajasthan'),
        ('09', 'Uttar Pradesh'),
        ('06', 'Haryana'),
        ('07', 'Delhi'),
        ('03', 'Punjab'),
        ('06', 'Haryana'),
        ('19', 'West Bengal'),
        ('10', 'Bihar'),
        ('20', 'Jharkhand'),
        ('21', 'Odisha'),
        ('32', 'Kerala'),
        ('30', 'Goa'),
    ]
    for code, name in indian_states:
        State.objects.get_or_create(code=code, defaults={'name': name, 'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_units, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_default_countries, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_default_states, reverse_code=migrations.RunPython.noop),
    ]
