# Generated by Django 6.0.4 on 2026-04-25 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('freight', '0001_initial'),
        ('masters', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='core.company'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable', to='freight.freight'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='masters.party'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable', to='masters.purchaseorder'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='masters.transporter'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='core.company'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='masters.party'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='core.company'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.company'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.creditnote'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.freight'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.party'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.accountpayable'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.company'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.accountreceivable'),
        ),
        migrations.AddField(
            model_name='transporterbill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transporter_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporterbill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_bills', to='core.company'),
        ),
        migrations.AddField(
            model_name='transporterbill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transporter_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporterbill',
            name='freights',
            field=models.ManyToManyField(related_name='transporter_bills', to='freight.freight'),
        ),
        migrations.AddField(
            model_name='transporterbill',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='masters.transporter'),
        ),
        migrations.AddField(
            model_name='transporterbillpayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporterbillpayment',
            name='transporter_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='accounts.transporterbill'),
        ),
        migrations.AlterUniqueTogether(
            name='ledgeraccount',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='transporterbill',
            unique_together={('company', 'bill_number')},
        ),
    ]
