# Generated by Django 5.2.13 on 2026-04-24 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        ('sales', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('Physical_Count', 'Physical Count Correction'), ('Damage', 'Damaged Goods'), ('Expired', 'Expired Goods'), ('Theft', 'Theft/Loss'), ('Other', 'Other')], max_length=20)),
                ('old_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='masters.item')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Purchase Receipt'), ('IN_RETURN', 'Sale Return'), ('IN_ADJUSTMENT', 'Stock Adjustment (+)'), ('OUT_SALE', 'Sale Dispatch'), ('OUT_CONSUMPTION', 'Internal Consumption'), ('OUT_ADJUSTMENT', 'Stock Adjustment (-)'), ('OUT_TRANSFER', 'Inter-Company Transfer')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.item')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='masters.purchaseorder')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity reserved for pending dispatches', max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='masters.item')),
            ],
            options={
                'verbose_name': 'Stock',
                'ordering': ['item__item_name'],
                'unique_together': {('company', 'item')},
            },
        ),
    ]
