# Generated by Django 6.0.5 on 2026-05-11 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CANCEL', 'Cancel'), ('LOAD', 'Load'), ('CHANGE_VEHICLE', 'Change Vehicle'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SELECT_COMPANY', 'Select Company'), ('GENERATE_INVOICE', 'Generate Invoice'), ('GENERATE_CREDIT_NOTE', 'Generate Credit Note'), ('REVERSE', 'Reverse'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
