# Generated by Django 5.2.13 on 2026-04-24 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Loaded', 'Loaded'), ('InTransit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=255)),
                ('delivery_remarks', models.TextField(blank=True)),
                ('pod_reference', models.CharField(blank=True, max_length=100, verbose_name='POD Reference')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vehicles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
                ('loading_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='masters.loadingpoint')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='masters.party')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='masters.transporter')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_vehicle_number', models.CharField(max_length=20)),
                ('new_vehicle_number', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_changes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Change Log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unloaded_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_items', to='masters.item')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Item',
                'unique_together': {('vehicle', 'item')},
            },
        ),
    ]
