# Generated by Django 5.2.13 on 2026-04-24 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('financial_year', models.CharField(max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='masters.party')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Sale',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=100, unique=True)),
                ('credit_note_date', models.DateField(auto_now_add=True)),
                ('financial_year', models.CharField(max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cn_type', models.CharField(choices=[('Full', 'Full Vehicle Rejection'), ('Shortage', 'Material Shortage'), ('Value', 'Value Deficiency (Service)')], default='Full', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='masters.party')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='vehicles.vehicle')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'ordering': ['-credit_note_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_type', models.CharField(max_length=20)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hsn_code', models.CharField(max_length=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='masters.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('vehicle_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='vehicles.vehicleitem')),
            ],
            options={
                'verbose_name': 'Sale Item',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_type', models.CharField(max_length=20)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hsn_code', models.CharField(max_length=8)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.creditnote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='masters.item')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Credit Note Item',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=10)),
                ('last_number', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cn_sequences', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=10)),
                ('last_number', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'financial_year')},
            },
        ),
    ]
