# Generated by Django 6.0.4 on 2026-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_creditnote_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='cn_type',
            field=models.CharField(choices=[('Full', 'Full Vehicle Rejection'), ('Shortage', 'Material Shortage'), ('Value', 'Value Deficiency (Service)')], default='Full', max_length=20),
        ),
    ]
