# Generated by Django 6.0.4 on 2026-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_creditnote_cn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
